### ISSUE TITLE
augmentation

### ISSUE THREAD

**Issue by howardchina** [ArdhenduBehera/cap#14]
https://github.com/ArdhenduBehera/cap/blob/cae53050af583c2b3fa38081c0abc227199e7dc1/image_datagenerator.py#L144

Does resize, crop, shift, rotate are the only need for the augmentation.
No brightness augmentation?

**Comment by ArdhenduBehera** [comment]
Yes, that's right.

**Comment by howardchina** [comment]
> Yes, that's right.

thx! :/
